version: '3'

services:
  db-auth:
    image: 'postgres:15.2'
    container_name: 'spa'
    environment:
      - 'POSTGRES_DB=spa_db'
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_PASSWORD=postgres'
    ports:
      - '5433:5432'