server:
#  servlet:
#    context-path: /api
  port: 9000

springdoc:
  show-actuator: true
  api-docs:
    groups:
      enabled: true

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/spa_db
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
  mail:
    host: smtp.gmail.com
    port: 587
    username: singleplaceassistent@gmail.com
    password: vmxefclupbhjzupk
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

application:
  frontUrl: http://CHANGE_ME:666
  mockEmailSending: false
  jwt:
    secretKey: securesecuresecuresecuresecuresecuresecuresecuresecuresecuresecuresecuresecuresecuresecure
    tokenPrefix: Bearer.
    tokenExpiration: 100
  allowed:
    origins: http://alwertus.zapto.org
    methods: GET,POST,PUT,DELETE
    headers: Authorization,Cache-Control,Content-Type