application:
  frontUrl: http://localhost:3000
  mockEmailSending: true
  allowed:
    origins: http://localhost:3000
    methods: GET,POST,PUT,DELETE
    headers: Authorization,Cache-Control,Content-Type