server:
  servlet:
    context-path: /api

springdoc:
  show-actuator: true
  api-docs:
    groups:
      enabled: true

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/spa_db
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
  mail:
    host: smtp.gmail.com
    port: 587
    username: singleplaceassistent@gmail.com
    password: vmxefclupbhjzupk
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

application:
  frontUrl: http://localhost:3000
  mockEmailSending: false
  jwt:
    secretKey: securesecuresecuresecuresecuresecuresecuresecuresecuresecuresecuresecuresecuresecuresecure
    tokenPrefix: Bearer.
    tokenExpiration: 100